// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIoTpsBQbokOt3IaglUWEOFtKe71ly8e0',
    appId: '1:198771364890:web:107d6501e53abc5e272da3',
    messagingSenderId: '198771364890',
    projectId: 'mic-factory',
    authDomain: 'mic-factory.firebaseapp.com',
    storageBucket: 'mic-factory.appspot.com',
    measurementId: 'G-C0Q6GNZHGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqLIvf6YZe08a_JADKTbF4N1qldvJI7yE',
    appId: '1:198771364890:android:4f46a3bfc2de7ae9272da3',
    messagingSenderId: '198771364890',
    projectId: 'mic-factory',
    storageBucket: 'mic-factory.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPxwvF7uLVKAGK14szeJAg06hpfSn3Ets',
    appId: '1:198771364890:ios:e98a8d7de06434e5272da3',
    messagingSenderId: '198771364890',
    projectId: 'mic-factory',
    storageBucket: 'mic-factory.appspot.com',
    iosBundleId: 'com.example.micFactory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPxwvF7uLVKAGK14szeJAg06hpfSn3Ets',
    appId: '1:198771364890:ios:17e31dc692a8e5c3272da3',
    messagingSenderId: '198771364890',
    projectId: 'mic-factory',
    storageBucket: 'mic-factory.appspot.com',
    iosBundleId: 'com.example.micFactory.RunnerTests',
  );
}
